/**
 * Seed data for Catholic saints
 * Auto-generated from Firestore by scripts/extract-patronages-firestore.js
 * Generated: 2025-11-13T20:47:24.983Z
 */

import type { Saint } from './types'

export const SEED_SAINTS: Saint[] = [
  {
    slug: "adelaide",
    displayName: "St. Adelaide",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Adelaide%20DougBarber.jpg",
  },
  {
    slug: "agatha",
    displayName: "St. Agatha",
    feastDay: "02-05",
    era: "3rd century",
    deathDate: "c. 250",
    birthPlace: "Catania, Sicily",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Martirio%20de%20Santa%20%C3%81gueda%2C%20por%20Sebastiano%20del%20Piombo.jpg",
  },
  {
    slug: "andrew",
    displayName: "St. Andrew the Apostle",
    feastDay: "11-30",
    era: "1st century",
    deathDate: "60",
    birthPlace: "Bethsaida, Galilee",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Martirio%20de%20San%20Andr%C3%A9s%2C%20por%20Juan%20Correa%20de%20Vivar.jpg",
  },
  {
    slug: "anthony-of-padua",
    displayName: "St. Anthony of Padua",
    era: "4th and 5th century",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/%28Venice%29%20Sant%27Antonio%20da%20Padova%20by%20Alvise%20Vivarini%20-%20Correr%20Museum.jpg",
  },
  {
    slug: "augustine-of-hippo",
    displayName: "St. Augustine of Hippo",
    patronages: ["brewers", "printers", "theologians", "sore eyes", "number of cities", "dioceses"],
    era: "4th century",
    birthDate: "354",
    birthPlace: "Tagaste, Numidia",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Augustine%20Lateran.jpg",
  },
  {
    slug: "benedict-of-nursia",
    displayName: "St. Benedict",
    patronages: ["europe", "monks", "kidney disease", "schoolchildren", "spelunkers", "against poison"],
    era: "6th century",
    birthDate: "c. 480",
    deathDate: "543",
    birthPlace: "Nursia, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Benedict%20I.jpg",
  },
  {
    slug: "bernadette-soubirous",
    displayName: "St. Bernadette Soubirous",
    patronages: ["bodily illness", "lourdes", "shepherds", "shepherdesses", "people ridiculed for their faith"],
    era: "13th century",
    birthPlace: "Aquitaine, France",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Bernadette%20Soubirous.jpg",
  },
  {
    slug: "blaise",
    displayName: "St. Blaise",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Dreux-Blaise.jpg",
  },
  {
    slug: "brigid-of-ireland",
    displayName: "St. Brigid of Ireland",
    feastDay: "02-01",
    patronages: ["ireland", "dairymaids", "cattle", "midwives", "irish nuns", "newborns"],
    era: "6th century",
    birthDate: "c. 451",
    deathDate: "525",
    birthPlace: "Faughart, Ireland",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Stbrigid.jpg",
  },
  {
    slug: "catherine-of-alexandria",
    displayName: "St. Catherine of Alexandria",
    feastDay: "11-25",
    patronages: ["philosophers", "students", "unmarried girls", "apologists", "wheelwrights"],
    era: "4th century",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Luini.%20Katerina.jpg",
  },
  {
    slug: "catherine-of-siena",
    displayName: "St. Catherine of Siena",
    era: "14th century",
    birthDate: "1347",
    deathDate: "1380",
    birthPlace: "Siena, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Santa%20Catalina%20de%20Siena%2C%20Pedro%20de%20Villegas%20Marmolejo.jpg",
  },
  {
    slug: "cecilia",
    displayName: "St. Cecilia",
    feastDay: "11-22",
    era: "4th century",
    birthPlace: "Rome, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Giambattista%20Tiepolo%20-%20Saint%20Cecilia%20-%20Google%20Art%20Project.jpg",
  },
  {
    slug: "christopher",
    displayName: "St. Christopher",
    patronages: ["travelers", "motorists", "sailors", "storms", "bachelors", "gardeners"],
    era: "3rd century",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Prince%20Brussels%201986%20%28retouched%29.jpg",
  },
  {
    slug: "dominic-guzman",
    displayName: "St. Dominic",
    feastDay: "08-06",
    era: "13th century",
    birthDate: "c. 1170",
    deathDate: "1221",
    birthPlace: "Calaroga, Spain",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Monmouth%20VIPs%20Bishop%20Dominic%20Walker.jpg",
  },
  {
    slug: "elizabeth-ann-seton",
    displayName: "St. Elizabeth Ann Seton",
    feastDay: "10-07",
    era: "4th century",
    deathDate: "303",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Elizabeth%20Ann%20Seton%20portrait%20by%20Amabilia%20Filicchi%20%28cropped%29.jpg",
  },
  {
    slug: "elizabeth-of-hungary",
    displayName: "St. Elizabeth of Hungary",
    feastDay: "11-17",
    patronages: ["bakers", "beggars", "brides", "charities", "death of children", "homeless people", "hospitals", "sisters of mercy", "widows"],
    era: "13th century",
    birthDate: "1207",
    deathDate: "1231",
    birthPlace: "Pressburg, Hungary",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Marburg%20Elisabethkirche%20Elisabethschrein%20Elisabethfigur.jpg",
  },
  {
    slug: "faustina-kowalska",
    displayName: "St. Faustina Kowalska",
    patronages: ["mercy"],
    era: "20th century",
    birthDate: "1905",
    birthPlace: "Głogowiec, Poland",
  },
  {
    slug: "ferdinand-iii",
    displayName: "St. Ferdinand III of Castile",
    era: "15th century",
    birthDate: "c. 1383",
    deathDate: "1451",
  },
  {
    slug: "francis-of-assisi",
    displayName: "St. Francis of Assisi",
    feastDay: "10-04",
    era: "13th century",
    birthDate: "c. 1181",
    deathDate: "1226",
    birthPlace: "Assisi, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/StFrancis%20part.jpg",
  },
  {
    slug: "george",
    displayName: "St. George",
    patronages: ["england", "soldiers", "archers", "cavalry", "chivalry", "farmers", "field workers", "riders", "saddlers", "scouts"],
    era: "early centuries",
    birthPlace: "Lydda, Palestine",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Giorgos%20Vovoras%20%28March%202021%29.png",
  },
  {
    slug: "gerard-majella",
    displayName: "St. Gerard Majella",
    era: "17th century",
    birthDate: "1579",
    deathDate: "1601",
    birthPlace: "Pibrac, France",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/San%20Gerardo%20Maiella.jpg",
  },
  {
    slug: "gianna-beretta-molla",
    displayName: "St. Gianna Beretta Molla",
    feastDay: "04-28",
    era: "20th century",
    birthDate: "1922",
    deathDate: "1962",
    birthPlace: "Magenta, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/GiannaBerettaMolla.jpg",
  },
  {
    slug: "ignatius-of-loyola",
    displayName: "St. Ignatius of Loyola",
    feastDay: "07-31",
    patronages: ["society of jesus", "soldiers", "educators", "education"],
    era: "16th century",
    birthDate: "c. 1491",
    deathDate: "1556",
    birthPlace: "Azpeitia, Spain",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/St%20Ignatius%20of%20Loyola%20%281491-1556%29%20Founder%20of%20the%20Jesuits.jpg",
  },
  {
    slug: "joan-of-arc",
    displayName: "St. Joan of Arc",
    era: "15th century",
    birthDate: "c. 1412",
    deathDate: "1431",
    birthPlace: "Domremy, France",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Contemporaine%20afb%20jeanne%20d%20arc.png",
  },
  {
    slug: "john-henry-newman",
    displayName: "St. John Henry Newman",
    feastDay: "10-09",
    era: "19th century",
    birthDate: "1801",
    deathDate: "1890",
    birthPlace: "London, England",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/John%20Henry%20Newman%20by%20Sir%20John%20Everett%20Millais%2C%201st%20Bt.jpg",
  },
  {
    slug: "john-the-apostle",
    displayName: "St. John the Apostle",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Rubens%20apostel%20johannes%20grt.jpg",
  },
  {
    slug: "josemaria-escriva",
    displayName: "St. Josemaría Escrivá",
    patronages: ["diabetes", "diocese of segovia", "spain"],
    era: "20th century",
    birthDate: "1902",
    birthPlace: "Barbastro, Spain",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Josemaria%20Escriva.jpg",
  },
  {
    slug: "joseph",
    displayName: "St. Joseph",
    patronages: ["of st"],
    birthDate: "c. 1",
    birthPlace: "Bethlehem, Israel",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/SantaFioraSanGiuseppe2.jpg",
  },
  {
    slug: "josephine-bakhita",
    displayName: "St. Josephine Bakhita",
    patronages: ["sudan", "human trafficking survivors"],
    era: "20th century",
    birthDate: "1869",
    deathDate: "1947",
    birthPlace: "Sudan",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Bakhita%20Szent%20Jozefina.jpeg",
  },
  {
    slug: "juan-diego",
    displayName: "St. Juan Diego",
    era: "18th century",
    birthDate: "1751",
    deathDate: "1816",
    birthPlace: "Cuvilly, France",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Juan-Diego.jpg",
  },
  {
    slug: "jude-thaddaeus",
    displayName: "St. Jude Thaddaeus",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Anthonis%20van%20Dyck%20088.jpg",
  },
  {
    slug: "louis-ix",
    displayName: "St. Louis IX of France",
    era: "13th century",
    birthDate: "c. 1214",
    deathDate: "1270",
    birthPlace: "Poissy, France",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Premier%20sceau%20de%20majest%C3%A9%20de%20Louis%20IX%20d%C3%A9tour%C3%A9.png",
  },
  {
    slug: "lucy",
    displayName: "St. Lucy",
    feastDay: "12-13",
    patronages: ["blind", "those with eye illnesses", "poor", "authors", "martyrs"],
    era: "3rd century",
    birthDate: "c. 283",
    deathDate: "303",
    birthPlace: "Syracuse, Sicily",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Maloja%20IMO%205218561%20G%20Hamburg%2007-1973%20%281%29.jpg",
  },
  {
    slug: "luke",
    displayName: "St. Luke the Evangelist",
    era: "1st century",
    birthDate: "c. 1",
    birthPlace: "Antioch, Syria",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Grandes%20Heures%20Anne%20de%20Bretagne%20Saint%20Luc.jpg",
  },
  {
    slug: "mary-magdalene",
    displayName: "St. Mary Magdalene",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Adam%20Camerarius%20-%20Treurende%20vrouw%20-%20Maria%20Magdalena%20-%20RH.S.185%20-%20Rubenshuis.tiff",
  },
  {
    slug: "matthew",
    displayName: "St. Matthew the Apostle",
    feastDay: "05-14",
    era: "1st century",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Anthony%20van%20Dyck%20-%20De%20apostel%20Mattheus%20-%20L%27apotre%20Matthieu%20-%20Fonds%20Generet%20-%20Koning%20Boudewijnstichting%20-%20Fondation%20Roi%20Baudouin.jpg",
  },
  {
    slug: "monica",
    displayName: "St. Monica",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Monica%20Sep%202019%20%282%29.png",
  },
  {
    slug: "patrick",
    displayName: "St. Patrick",
    feastDay: "03-17",
    era: "5th century",
    birthDate: "c. 387",
    deathDate: "493",
    birthPlace: "Kilpatrick, Scotland",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Saint%20Patrick%20Catholic%20Church%20%28Junction%20City%2C%20Ohio%29%20-%20stained%20glass%2C%20Saint%20Patrick%20-%20detail.jpg",
  },
  {
    slug: "paul",
    displayName: "St. Paul the Apostle",
    patronages: ["missionaries", "evangelists", "writers", "journalists", "authors", "public workers", "rope", "saddle makers", "tent makers"],
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Giovanni%20Francesco%20Barbieri%20-%20Saint%20Paul.jpg",
  },
  {
    slug: "peter",
    displayName: "St. Peter the Apostle",
    era: "1st century",
    birthDate: "c. 1",
    deathDate: "c. 64",
    birthPlace: "Bethsaida, Israel",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Pope-peter%20pprubens.jpg",
  },
  {
    slug: "philomena",
    displayName: "St. Philomena",
    era: "16th century",
    birthDate: "c. 1560",
    birthPlace: "England",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Tela%20di%20Santa%20Filomena.jpg",
  },
  {
    slug: "padre-pio",
    displayName: "St. Pio of Pietrelcina",
    era: "20th century",
    birthDate: "1887",
    deathDate: "1968",
    birthPlace: "Pietrelcina, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Padre%20Pio%20portrait.jpg",
  },
  {
    slug: "rita-of-cascia",
    displayName: "St. Rita of Cascia",
    patronages: ["impossible causes", "difficult marriages", "infertility", "parenthood", "sickness"],
    era: "19th century",
    birthDate: "1800",
    deathDate: "1886",
    birthPlace: "Walton, England",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/S.Rita%20da%20Cascia.jpg",
  },
  {
    slug: "rose-of-lima",
    displayName: "St. Rose of Lima",
    patronages: ["peru", "indigenous people of latin america", "embroiderers", "gardeners", "florists", "those who suffer ridicule for their piety"],
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Santa%20Rosa%20de%20Lima%20Ebrafol.jpg",
  },
  {
    slug: "sebastian",
    displayName: "St. Sebastian",
    feastDay: "01-20",
    patronages: ["archers", "athletes", "those who desire a saintly death", "those suffering from plagues"],
    era: "3rd century",
    deathDate: "286",
    birthPlace: "Milan, Italy",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Simon%20Rex%20during%20an%20interview%2C%20March%202022.jpg",
  },
  {
    slug: "teresa-benedicta",
    displayName: "St. Teresa Benedicta of the Cross",
    era: "20th century",
    birthDate: "1891",
    deathDate: "1942",
    birthPlace: "Breslau, Germany",
  },
  {
    slug: "teresa-of-avila",
    displayName: "St. Teresa of Avila",
    feastDay: "10-04",
    era: "16th century",
    birthDate: "1515",
    deathDate: "1582",
    birthPlace: "Avila, Spain",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Santa%20Teresa%20de%20Jes%C3%BAs%20%28Museo%20del%20Prado%29.jpg",
  },
  {
    slug: "teresa-of-calcutta",
    displayName: "St. Teresa of Calcutta",
    era: "20th century",
    birthDate: "1910",
    deathDate: "1997",
    birthPlace: "Skopje, Albania",
  },
  {
    slug: "therese-of-lisieux",
    displayName: "St. Thérèse of Lisieux",
    patronages: ["florists", "missionaries", "france", "russia", "hiv/aids sufferers", "tuberculosis sufferers"],
    era: "19th century",
    birthDate: "1820",
    deathDate: "1889",
    birthPlace: "Amsterdam, Netherlands",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Teresa-de-Lisieux.jpg",
  },
  {
    slug: "thomas-aquinas",
    displayName: "St. Thomas Aquinas",
    feastDay: "03-07",
    era: "13th century",
    birthDate: "c. 1225",
    deathDate: "1274",
    birthPlace: "Rocca Secca, Kingdom of Naples",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/St-thomas-aquinasFXD.jpg",
  },
  {
    slug: "valentine",
    displayName: "St. Valentine",
    feastDay: "02-14",
    patronages: ["love", "young people", "happy marriages", "beekeepers", "epilepsy", "travelers"],
    era: "3rd century",
    imageUrl: "http://commons.wikimedia.org/wiki/Special:FilePath/Macchina%20da%20scrivere%20valentine%2C%20ettore%20sottsass%2C%201969.JPG",
  },
  {
    slug: "charbel",
    displayName: "St. Charbel",
    feastDay: "07-24",
    era: "19th century",
    birthDate: "1828",
    deathDate: "1898",
    birthPlace: "Bekaa Kafra, Lebanon",
  },
]
